kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: leangoo-ingress
  namespace: demo-test
  labels:
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/version: v1
  annotations:
    kubesphere.io/creator: admin
    nginx.ingress.kubernetes.io/upstream-vhost: new-t.leangoo.com
    proxy-real-ip-cide: "127.0.0.6/32,10.233.107.21/32"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx
                port:
                  number: 80
