apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s-hello-world-app.yaml
- k8s-nginx.yaml
- k8s-ingress.yaml

configMapGenerator:
- name: hello-world-configmap-files
  files:
    - hello-world.com.conf=./hello-world.com.conf
